In [1]:
import numpy as np
import pandas as pd

import os
import sys

In [37]:
PATH_TO_SEISM_SIGNAL = "../1__Preproc_data/Seism_analise/Wells_seism.csv" 
PATH_TO_SEISM_Z = "../1__Preproc_data/Seism_analise/Wells_index_seism.csv" 
df_sig = pd.read_csv(PATH_TO_SEISM_SIGNAL, sep=";")
df_sig.set_index("z_m_index", inplace=True)

df_z = pd.read_csv(PATH_TO_SEISM_Z, sep=";")
df_z.set_index("z_m_index", inplace=True)

In [38]:
df_sig

,g274,g276,g277,g278,g279,g280,g281,g282,g288,g291,...,g551,g552,g553,g554,g555,g556,g557,g558,g559,g581
z_m_index,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1899,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
df_z

,g274,g276,g277,g278,g279,g280,g281,g282,g288,g291,...,g551,g552,g553,g554,g555,g556,g557,g558,g559,g581
z_m_index,,,,,,,,,,,,,,,,,,,,,
0,736.918692,988.574766,1350.147370,1533.059453,1595.602267,1591.447451,1595.643154,1690.137387,337.680419,1066.424427,...,901.244653,219.977501,925.985838,1157.933655,1349.961123,1220.310327,1550.054086,1304.325659,1386.685455,2208.731053
1,739.016303,990.341121,1351.543590,1534.259853,1596.710579,1592.617698,1596.813033,1691.191331,340.594630,1068.164885,...,903.414832,222.481741,927.917437,1159.799035,1351.378231,1222.274296,1551.709729,1305.933026,1388.118182,2209.958711
2,741.113915,992.107477,1352.939809,1535.460253,1597.818892,1593.787945,1597.982913,1692.245276,343.508841,1069.905344,...,905.585012,224.985981,929.849037,1161.664415,1352.795339,1224.238264,1553.365372,1307.540393,1389.550909,2211.186369
3,743.211526,993.873832,1354.336028,1536.660654,1598.927204,1594.958192,1599.152793,1693.299220,346.423052,1071.645802,...,907.755191,227.490220,931.780636,1163.529796,1354.212447,1226.202233,1555.021016,1309.147761,1390.983636,2212.414028
4,745.309138,995.640187,1355.732248,1537.861054,1600.035516,1596.128439,1600.322673,1694.353165,349.337263,1073.386260,...,909.925371,229.994460,933.712235,1165.395176,1355.629554,1228.166201,1556.676659,1310.755128,1392.416364,2213.641686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1896,4713.990343,4337.584112,3997.379263,3809.018106,3696.962469,3810.235524,3813.735096,3688.416152,5863.024231,4366.332824,...,5015.905074,4968.015941,4588.297977,4694.694510,4036.797388,4943.994671,4689.153723,4351.893679,4103.136364,4536.371421
1897,4716.087954,4339.350467,3998.775482,3810.218506,3698.070781,3811.405771,3814.904976,3689.470097,5865.938441,4368.073282,...,5018.075254,4970.520181,4590.229576,4696.559890,4038.214495,4945.958640,4690.809366,4353.501046,4104.569091,4537.599079
1898,4718.185566,4341.116822,4000.171701,3811.418906,3699.179093,3812.576018,3816.074856,3690.524041,5868.852652,4369.813740,...,5020.245433,4973.024421,4592.161175,4698.425270,4039.631603,4947.922608,4692.465010,4355.108414,4106.001818,4538.826738
1899,4720.283178,4342.883178,4001.567921,3812.619306,3700.287406,3813.746265,3817.244736,3691.577986,5871.766863,4371.554198,...,5022.415613,4975.528660,4594.092775,4700.290650,4041.048711,4949.886577,4694.120653,4356.715781,4107.434545,4540.054396
1900,4722.380789,4344.649533,4002.964140,3813.819707,3701.395718,3814.916512,3818.414615,3692.631930,5874.681074,4373.294656,...,5024.585792,4978.032900,4596.024374,4702.156030,4042.465819,4951.850546,4695.776296,4358.323148,4108.867273,4541.282055

In [40]:
z_m_new = np.arange(0, 3729, 4)
new_df_matrix = []
for col in df_z.columns:
    new_df_matrix.append(np.interp(z_m_new, df_z[col], df_sig[col]))

new_df_matrix = np.array(new_df_matrix).T

In [43]:
df_reindex_seism = pd.DataFrame(new_df_matrix, index = z_m_new, columns=df_z.columns)
df_reindex_seism

,g274,g276,g277,g278,g279,g280,g281,g282,g288,g291,...,g551,g552,g553,g554,g555,g556,g557,g558,g559,g581
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3712,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3716,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3724,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3728,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [44]:
df_reindex_seism.to_csv("Reindex_seism.csv", sep=";")
df_reindex_seism.to_csv("Reindex_seism.xlsx")